name: Build

on:
  push:
    branches: [main, feature/gh-workflows]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller

      - name: Install dependencies
        run: |
          pip config set global.extra-index-url https://download.pytorch.org/whl/cu121
          pip install -e .

      - name: Build Wheel
        run: |
          python -m build --wheel --outdir dist

      - name: Build Executable
        run: |
          pyinstaller --onefile __main__.py --name mktrain

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/mktrain*
